<MyScreenManager>:

    Screen1:
        name: 'screen1'

<Screen1>:

    BoxLayout:

        orientation: 'vertical'

        GridLayout:

            cols: 3
            padding: 20
            spacing: 20
            size_hint: 1, .1

            Label:
                text: 'List of Widgets'
                underline: True
            Label:
                text: 'Percentage'
                underline: True
            Label:
                text: 'Remove (Y/N)'
                underline: True

        ScrollView:

            size_hint: 1, .5
            do_scroll_x: False
            padding: 20
            spacing: 20

            GridLayout:

                id: widget_list
                cols: 1
                spacing: 5

                GridLayout:
                    rows: 1
                    Label:
                        text: 'Nothing Here'

        GridLayout:

            cols: 3
            padding: 20
            spacing: 20
            size_hint: 1, .2

            Button:
                text: 'Add Widget'
                on_release: root.add()

            Label:
                text: ''

            Button:
                text: 'Remove Widget'
                on_release: root.remove()